In [1]:
import numpy as np

In [2]:
# Create an array from a list
a = np.array([1,2,3])
print("Array a:", a)

Array a: [1 2 3]


In [3]:
b = np.arange(0,10,2)
print("Array b:", b)

Array b: [0 2 4 6 8]


In [4]:
c = np.arange(0,15,4)
print("Array c:", c)

Array c: [ 0  4  8 12]


In [5]:
c1 = np.arange(0,15,3)
print("Array c1:", c1)

Array c1: [ 0  3  6  9 12]


In [6]:
d = np.zeros((2,3),)
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
d = np.zeros((3,5),)
print("Array d:\n", d)

Array d:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
d = np.zeros((5,2),)
print("Array d:\n", d)

Array d:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
d = np.zeros((2,3),dtype=int)
print("Array d:\n", d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [10]:
d = np.zeros((3,5),dtype=int)
print("Array d:\n", d)

Array d:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [11]:
e = np.ones((3,2))
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
e = np.ones((5,3))
print("Array e:\n", e)

Array e:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
f = np.eye(4)
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [14]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [16]:
a2 = np.array([1,2,3])
reshaped = np.reshaped(a2,(1,3))
print("Reshaped array:", reshaped)

AttributeError: module 'numpy' has no attribute 'reshaped'

In [17]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1))
print("Reshaoed array:", reshaped)

Reshaoed array: [[1]
 [2]
 [3]]


In [18]:
a2 = np.array([1,2,3,4])
reshaped = np.reshape(a2,(4,1))
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]
 [4]]


In [19]:
f1 = np.array([[1,2],[3,4],[5,6],[7,8]])
flattend = np.ravel(f1)
print("Flattend array:", flattend)

Flattend array: [1 2 3 4 5 6 7 8]


In [20]:
f2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattend = np.ravel(f2)
print("Flattend array:", flattend)

Flattend array: [ 1  2  3  4  5  6  7  8  9 10]


In [21]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


# Mathematical Functions

In [22]:
g = np.array([1,2,3,4])
added = np.add(g,2)
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [23]:
g = np.array([1,2,3,4,5])
added = np.add(g,2)
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6 7]


In [24]:
square = np.power(g,2)
print("Square g:", square)

Square g: [ 1  4  9 16 25]


In [25]:
sqrt_val = np.sqrt(g)
print("square root of g:", sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.         2.23606798]


In [26]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4 5]


In [27]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [28]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a)
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


In [30]:
a4 = np.array([1,2,3,4])
dot_product = np.dot(a2,a)
print("Dot product of a2 and a:", dot_product)

ValueError: shapes (4,) and (3,) not aligned: 4 (dim 0) != 3 (dim 0)

# 4 Statistical Functions

In [32]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [33]:
s = np.array([1,2,3,4,5])
mean = np.mean(s)
print("mean of s:", mean)

mean of s: 3.0


In [34]:
std_dev = np.std(s)
print("standard deviation of s:", std_dev)

standard deviation of s: 1.4142135623730951


In [35]:
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [36]:
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 5


# 5. Linear Algebra Functions

In [37]:
matrix = np.array([[1,2],[3,4]])

# 6. Ramdom Sampling Functions

In [38]:
random_vals = np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.7655217  0.8254428  0.35882709]


In [39]:
np.random.seed(0)
random_vals = np.random.rand(3)
print("Random Values:",random_vals)

Random Values: [0.5488135  0.71518937 0.60276338]


In [40]:
rand_ints = np.random.randint(0, 10, size=5)
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [41]:
np.random.seed(0)
rand_ints = np.random.randint(0, 10, size=5)
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7.Boolean & Logical Functions

In [42]:
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)
print("All element True:", all_true)

All element True: False


In [43]:
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)
print("All Elements True:", all_true)

All Elements True: False


In [46]:
any_true = np.any(logical_test)
print("All elements True:", any_true)

All elements True: False


In [47]:
any_true = np.any(logical_test)
print("All elements True:", any_true)

All elements True: False


# 8. Set Operations

In [48]:
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [49]:
union = np.array(set_a, set_b)
print("Union of a and b:", union)

TypeError: Cannot construct a dtype from an array

In [50]:
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9. Array Attribute Functions

In [53]:
a = np.array([1,2,3])
shape = a.shape
size = a.size
dimensions = a.ndim
dtype = a.dtype

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# 10. Other Functions

In [54]:
a = np.array([1,2,3])
copied_array = np.copy(a)
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [55]:
array_size_in_bytes = a.nbytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [56]:
shared = np.shares_memory(a, copied_array)
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
