In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
np.arange(3)

array([0, 1, 2])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
np.arange(6.0)

array([0., 1., 2., 3., 4., 5.])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [20]:
np.arange(20,10)

array([], dtype=int64)

In [21]:
np.arange(8,2)

array([], dtype=int64)

In [22]:
np.arange(9,0)

array([], dtype=int64)

In [23]:
np.arange(-20, 5)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4])

In [24]:
np.arange(10,-5)

array([], dtype=int64)

In [25]:
np.arange(-16,0)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1])

In [26]:
np.arange(-5,8)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [27]:
np.arange(-56,-46)

array([-56, -55, -54, -53, -52, -51, -50, -49, -48, -47])

In [28]:
np.arange(-20,-15)

array([-20, -19, -18, -17, -16])

In [29]:
ar = np.arange(10,29)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28])

In [30]:
ar = np.arange(-15,5)
ar

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
        -2,  -1,   0,   1,   2,   3,   4])

In [31]:
ar = np.arange(-10,5)
ar

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

In [33]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [34]:
np.arange()

TypeError: arange() requires stop to be specified.

In [35]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [36]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [37]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [38]:
np.arange(10,30,5,3)

TypeError: Cannot interpret '3' as a data type

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [43]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [44]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [47]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
np.zeros((4,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [50]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [51]:
zero = np.zeros([4,3])
print(zero)
print(type(zero))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [52]:
zero = np.zeros([3,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [55]:
zero = np.zeros([2,2])
print(zero)
print('###')
print(type(zero))

[[0. 0.]
 [0. 0.]]
###
<class 'numpy.ndarray'>


In [56]:
zero = np.zeros([4,3])
print(zero)
print('###')
print(type(zero))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
###
<class 'numpy.ndarray'>


In [57]:
zero = np.zeros([10,5])
print(zero)
print('###')
print(type(zero))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
###
<class 'numpy.ndarray'>


In [58]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [59]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.zeros((10,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.ones(3)

array([1., 1., 1.])

In [63]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [64]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [65]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [66]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [67]:
np.twos(4)

AttributeError: module 'numpy' has no attribute 'twos'

In [68]:
rand(3,2)

NameError: name 'rand' is not defined

In [69]:
random.rand(3,2)

NameError: name 'random' is not defined

In [70]:
np.random.rand(3,2)

array([[0.44137671, 0.49564938],
       [0.94968361, 0.57975709],
       [0.61494465, 0.44644269]])

In [71]:
np.random.rand(2,5)

array([[0.21632673, 0.23480764, 0.16533528, 0.54949304, 0.8720124 ],
       [0.58446447, 0.5703226 , 0.1636804 , 0.12792077, 0.97045485]])

In [72]:
np.random.rand(5,2)

array([[0.92332011, 0.86923369],
       [0.06235607, 0.0968784 ],
       [0.53864808, 0.2183978 ],
       [0.83770779, 0.14741313],
       [0.93945485, 0.42374281]])

In [77]:
np.random.randint(4,6)

5

In [78]:
np.random.randint(4,6)

5

In [79]:
np.random.randint(8,10)

9

In [80]:
np.random.randint(2,6)

3

In [81]:
np.random.randint(2,7)

6

In [82]:
np.random.randint(2,7)

3

In [83]:
np.random.randint(2,7)

4

In [86]:
np.random.randint(2,20,4)

array([13,  2, 10,  3], dtype=int32)

In [88]:
np.random.randint(5,20,5)

array([13,  7, 16, 14,  8], dtype=int32)

In [91]:
np.random.randint(5,100,50)

array([89, 19, 54, 10, 57, 64, 97, 35, 37, 64, 68, 57, 21, 52, 65, 57, 60,
       28, 53,  9, 29,  6, 24, 72, 26, 67, 63, 31, 48, 12,  7, 29, 95, 13,
       38,  6, 45, 70, 45, 60, 29, 87, 81, 43, 55, 31, 36, 36, 30, 51],
      dtype=int32)

In [92]:
np.random.randint(10,500,200)

array([265, 435, 131,  62, 186, 406,  14, 290,  51,  51, 209, 392, 109,
       191, 228, 421, 187, 288, 371, 412, 430, 453, 466,  31, 397, 342,
       446,  55, 240, 448, 385, 219, 316, 408, 282, 345, 486, 452, 338,
       466, 457, 379, 163, 172,  12, 438,  57, 340, 325, 487, 390, 382,
        31, 187, 138, 450, 333, 162,  90, 237,  17,  60, 187, 268, 133,
        40, 491, 303, 312,  95, 273, 381,  39, 225, 377, 490, 370, 259,
       163,  22, 145, 184, 238, 238,  40, 349, 298, 212, 442, 376, 438,
       353, 480, 138, 419,  39, 253, 408, 257, 488, 265, 261, 356,  69,
       274, 365, 443, 455,  23, 253, 480,  65, 193, 473, 137, 380, 135,
       168, 111, 386,  84, 424, 432, 213, 119, 250, 153, 428, 420, 364,
       443, 322, 245, 387, 150, 273, 450, 402, 228, 109, 461, 464, 118,
       306, 271, 466, 393, 433, 141, 344,  93, 494, 195, 295,  52, 123,
       498, 207, 498, 252, 237, 216,  43, 409, 183, 458, 114, 153,  73,
       245, 278, 267, 482, 139, 270,  18, 124, 206,  35, 143,  4

In [93]:
np.random.randint(30,20,2)

ValueError: low >= high

In [94]:
np.random.randint(40,20,5)

ValueError: low >= high

In [95]:
 np.random.randint(-30,20,10)

array([-20,  -7,   9,   2,  13,  12, -25,  -7,   3, -29], dtype=int32)

In [96]:
np.random.randint(-40,20,45)

array([  5, -21, -27, -11,  15,  19, -22, -12, -30,  -1, -40, -11, -30,
       -19, -26,   9, -24, -22,   4, -40,  13, -36,  -2,  13,  -4,  15,
       -19,  -8, -22, -20, -40,  18, -11,  12, -32,  13,  -8,   5,  -5,
       -21, -22,  -6, -21, -37,  -5], dtype=int32)

In [97]:
np.random.randint(-5,2,3)

array([-2, -4,  1], dtype=int32)

In [98]:
np.random.randint(20,30,10)

array([20, 28, 28, 29, 24, 21, 29, 27, 25, 25], dtype=int32)

In [100]:
np.random.randint(10,20,5)

array([18, 12, 13, 11, 15], dtype=int32)

In [101]:
np.random.rand(10,20,3)

array([[[0.36186969, 0.45539517, 0.72696104],
        [0.39448316, 0.68219714, 0.2631806 ],
        [0.81471035, 0.30656729, 0.03328511],
        [0.5173677 , 0.8487902 , 0.33125816],
        [0.33729014, 0.473443  , 0.4860553 ],
        [0.19545651, 0.92966605, 0.10513705],
        [0.89514162, 0.40957255, 0.91764489],
        [0.10411034, 0.84195391, 0.11519186],
        [0.98547084, 0.82076942, 0.50792268],
        [0.36168437, 0.44975337, 0.46455011],
        [0.48063606, 0.10141394, 0.6526838 ],
        [0.13327565, 0.02915912, 0.42890321],
        [0.48219213, 0.90050609, 0.12521239],
        [0.74404745, 0.49439159, 0.61975159],
        [0.93863941, 0.26366338, 0.96089857],
        [0.00269062, 0.63973677, 0.8885049 ],
        [0.81348668, 0.86976037, 0.22174546],
        [0.18034054, 0.06275076, 0.70626803],
        [0.98807712, 0.24059672, 0.90686414],
        [0.3993008 , 0.29128189, 0.0370765 ]],

       [[0.04591497, 0.7607984 , 0.69058431],
        [0.01580135, 0.22032253,

In [102]:
np.random.randint(10,40,(10,10))

array([[36, 10, 14, 30, 38, 22, 35, 34, 28, 38],
       [28, 25, 15, 20, 22, 25, 11, 23, 32, 23],
       [20, 19, 27, 35, 29, 38, 13, 17, 12, 10],
       [30, 12, 27, 28, 20, 30, 32, 11, 13, 10],
       [19, 21, 19, 33, 22, 35, 31, 32, 31, 21],
       [32, 23, 16, 38, 38, 11, 35, 34, 39, 20],
       [27, 15, 37, 30, 31, 27, 18, 12, 15, 34],
       [22, 22, 23, 16, 36, 29, 38, 32, 14, 26],
       [25, 25, 28, 22, 17, 22, 11, 19, 10, 15],
       [14, 13, 26, 24, 26, 23, 39, 14, 27, 10]], dtype=int32)

In [103]:
np.random.randint(4,5,(15,10))

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]], dtype=int32)

In [104]:
np.random.randint(2,15,(20,5))

array([[14,  2, 11,  6, 14],
       [ 5, 11,  4,  4,  5],
       [12,  6,  5, 10,  7],
       [10, 10,  6,  8, 10],
       [ 3,  7,  8, 10,  6],
       [10,  9,  8,  6, 13],
       [ 3, 10,  7, 12, 12],
       [ 5, 13, 10,  9,  2],
       [11,  5,  7, 13, 14],
       [ 5, 14,  7, 13,  9],
       [11, 14, 12,  8,  2],
       [ 6, 12,  4, 13,  9],
       [ 4, 11,  3, 14,  2],
       [ 4,  4,  9,  7,  5],
       [ 2, 12,  9,  6,  2],
       [ 7,  5, 10, 14, 13],
       [ 2,  9,  8,  8,  7],
       [ 5,  4, 14,  8, 10],
       [ 7,  6,  7, 13,  8],
       [ 5, 10, 11,  7, 14]], dtype=int32)

In [105]:
arr

array([0, 1, 2, 3, 4, 5])

In [106]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [111]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [113]:
np.arange(1,22).reshape(3,5)

ValueError: cannot reshape array of size 21 into shape (3,5)

In [114]:
np.arange(1,22).reshape(3,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [115]:
np.arange(1,22).reshape(7,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [116]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# Slicing in Matrix

In [119]:
b = np.random.randint(10,20(5,4))

TypeError: 'int' object is not callable

In [120]:
b = np.random.randint(10,20,(5,4))

In [121]:
b

array([[19, 16, 10, 16],
       [16, 19, 12, 13],
       [14, 13, 13, 16],
       [11, 16, 19, 16],
       [10, 19, 19, 13]], dtype=int32)

In [122]:
type(b)

numpy.ndarray

In [123]:
b[:]

array([[19, 16, 10, 16],
       [16, 19, 12, 13],
       [14, 13, 13, 16],
       [11, 16, 19, 16],
       [10, 19, 19, 13]], dtype=int32)

In [124]:
b[0]

array([19, 16, 10, 16], dtype=int32)

In [125]:
b[1]

array([16, 19, 12, 13], dtype=int32)

In [126]:
b[4]

array([10, 19, 19, 13], dtype=int32)

In [127]:
b[3]

array([11, 16, 19, 16], dtype=int32)

In [128]:
b[-3]

array([14, 13, 13, 16], dtype=int32)

In [129]:
b[-5]

array([19, 16, 10, 16], dtype=int32)

In [130]:
b[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [131]:
b[4]

array([10, 19, 19, 13], dtype=int32)

In [132]:
b[:]

array([[19, 16, 10, 16],
       [16, 19, 12, 13],
       [14, 13, 13, 16],
       [11, 16, 19, 16],
       [10, 19, 19, 13]], dtype=int32)

In [133]:
b[2]

array([14, 13, 13, 16], dtype=int32)

In [136]:
b[2:3]

array([[14, 13, 13, 16]], dtype=int32)

In [135]:
b[1:2]

array([[16, 19, 12, 13]], dtype=int32)