# Operations

In [4]:
import numpy as np

In [7]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
a = np.random.randint(10,20,10)

In [13]:
a

array([16, 14, 11, 13, 15, 16, 13, 10, 15, 13], dtype=int32)

In [14]:
id(a)

2042842623760

In [15]:
arr

array([0, 1, 2, 3, 4, 5])

In [16]:
arr2 =np.random.randint(0,100,(10,10))

In [17]:
arr2

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [71, 95, 85,  2, 56, 78, 48, 89, 11, 54]], dtype=int32)

In [20]:
arr3 = np.random.randint(1,50,(5,5))

In [21]:
arr3

array([[ 3, 10, 17,  1, 22],
       [ 6, 38, 19, 23, 38],
       [29, 38, 28,  9, 46],
       [20, 32, 18, 36, 40],
       [18, 26, 29,  8,  5]], dtype=int32)

In [22]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [23]:
arr

array([0, 1, 2, 3, 4, 5])

In [24]:
arr[:4]

array([0, 1, 2, 3])

In [25]:
arr[:2]

array([0, 1])

In [26]:
arr[:5]

array([0, 1, 2, 3, 4])

In [27]:
arr[:3]

array([0, 1, 2])

In [28]:
arr2[:]

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [71, 95, 85,  2, 56, 78, 48, 89, 11, 54]], dtype=int32)

In [29]:
arr2[0:5]

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62]], dtype=int32)

In [30]:
arr2

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [71, 95, 85,  2, 56, 78, 48, 89, 11, 54]], dtype=int32)

In [31]:
arr2[1,4]

np.int32(89)

In [32]:
arr2

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [71, 95, 85,  2, 56, 78, 48, 89, 11, 54]], dtype=int32)

In [33]:
arr2[-5,5]

np.int32(25)

In [34]:
arr2[-5,-5]

np.int32(25)

In [35]:
arr2[5,-6]

np.int32(74)

In [36]:
arr2[-8,6]

np.int32(70)

In [37]:
arr2[-1,-9]

np.int32(95)

In [38]:
arr2

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [71, 95, 85,  2, 56, 78, 48, 89, 11, 54]], dtype=int32)

In [39]:
arr2[-1,-2]

np.int32(11)

In [40]:
arr2

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [71, 95, 85,  2, 56, 78, 48, 89, 11, 54]], dtype=int32)

In [41]:
arr2[::-1]

array([[71, 95, 85,  2, 56, 78, 48, 89, 11, 54],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57]], dtype=int32)

In [42]:
arr2[::-3]

array([[71, 95, 85,  2, 56, 78, 48, 89, 11, 54],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57]], dtype=int32)

In [43]:
arr2

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [71, 95, 85,  2, 56, 78, 48, 89, 11, 54]], dtype=int32)

In [44]:
arr2[::-2]

array([[71, 95, 85,  2, 56, 78, 48, 89, 11, 54],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82]], dtype=int32)

In [45]:
arr2[::-4]

array([[71, 95, 85,  2, 56, 78, 48, 89, 11, 54],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82]], dtype=int32)

In [46]:
arr2[:-3]

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39]], dtype=int32)

In [47]:
arr2

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62],
       [21, 41, 60, 44, 74, 25, 12, 81, 86, 56],
       [42, 18, 51, 80, 46,  8,  2, 88, 30, 39],
       [68, 51, 73, 73, 87, 12, 27, 17, 16, 49],
       [41,  6, 99,  0, 86, 78, 39, 61, 84, 64],
       [71, 95, 85,  2, 56, 78, 48, 89, 11, 54]], dtype=int32)

In [48]:
arr2[:4]

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89]], dtype=int32)

In [49]:
arr2[:5]

array([[ 4, 99, 79, 79, 36, 32, 95,  2, 48, 57],
       [68, 54, 82, 17, 89, 60, 51, 27, 11, 82],
       [66,  6, 66,  4, 37, 99, 70, 12, 22, 58],
       [62, 87, 58, 46, 93, 51, 79, 76, 23, 89],
       [ 2, 64, 32, 10, 96, 88, 78, 52, 40, 62]], dtype=int32)

In [50]:
arr

array([0, 1, 2, 3, 4, 5])

In [51]:
arr.max()

np.int64(5)

In [52]:
arr.min()

np.int64(0)

In [53]:
arr.mean()

np.float64(2.5)

In [55]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [56]:
from numpy import *
a = array([1,2,3,4,5])
median(a)

np.float64(3.0)

In [60]:
from numpy import *
a1 = array([1,2,3,4,9])
median(a1)

np.float64(3.0)

In [61]:
from numpy import *
a1 = array([1,3,4,5,6,8,9])
median(a1)

np.float64(5.0)